Updated makefiles for T2'
The makefiles now have a target PQGT2P and PQGTP (T1 and T2').

diff --git a/Makefile.intel-32 b/Makefile.intel-32
--- a/Makefile.intel-32
+++ b/Makefile.intel-32
@@ -15,7 +15,8 @@ CPPSRC	= pd_sdp.cpp\
             PHM.cpp\
             SUP.cpp\
             EIG.cpp\
-	    DPM.cpp
+	    DPM.cpp\
+	    T2PM.cpp
 
 OBJ	= $(CPPSRC:.cpp=.o)
 
@@ -91,6 +92,30 @@ PQGT1:
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
 	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_1 conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGT2P:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q, G and T_2'\'' conditions'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGT2P"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_2'\'' conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGTP:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q, G, T_1 and T_2'\'' conditions'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGTP"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G, T_1 and T_2'\'' conditions successfully!'; \
 	   echo; \
 	 fi
 
diff --git a/Makefile.intel-64 b/Makefile.intel-64
--- a/Makefile.intel-64
+++ b/Makefile.intel-64
@@ -16,7 +16,8 @@ CPPSRC	= pd_sdp.cpp\
             DPM.cpp\
             PPHM.cpp\
             SUP.cpp\
-            EIG.cpp
+            EIG.cpp\
+	    T2PM.cpp
 
 OBJ	= $(CPPSRC:.cpp=.o)
 
@@ -105,6 +106,30 @@ PQGT:
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
 	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G, T_1 and T_2 conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGT2P:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q, G and T_2'\'' conditions'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGT2P"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_2'\'' conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGTP:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q, G, T_1 and T_2'\'' conditions'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGTP"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G, T_1 and T_2'\'' conditions successfully!'; \
 	   echo; \
 	 fi
 
