Updated makefile to different platforms
There are now 3 makefiles: two for intel icpc and mkl (32 and 64 bit) and
one for gcc + atlas. Copy the one you want to use to Makefile and
everything works as it should. Remember to change the Makefile.* and not
Makefile as only Makefile.* are in the git index. I'm working on a hook to
automatic update the Makefile.

diff --git a/Makefile.gcc b/Makefile.gcc
--- a/Makefile.gcc
+++ b/Makefile.gcc
@@ -24,18 +24,18 @@ OBJ	= $(CPPSRC:.cpp=.o)
 
 BRIGHT_ROOT= .
 
-INCLUDE = ./include
+INCLUDE = -Iinclude
 
-LIBS=
+LIBS= -llapack -lblas
 
-CC	= icc
-CXX	= icpc
+CC	= gcc
+CXX	= g++
 
 # -----------------------------------------------------------------------------
 #   Compiler & Linker flags
 # -----------------------------------------------------------------------------
-CFLAGS	= -I$(INCLUDE) -g -Wall -O2 -I/opt/intel/mkl/10.0.3.020/include/
-LDFLAGS	= -g -Wall -O2 -lmkl_lapack -lmkl_intel -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -L/opt/intel/mkl/10.0.3.020/lib/32/
+CFLAGS	= $(INCLUDE) -g -Wall -O2
+LDFLAGS	= $(LIBS) -g -Wall -O2
 
 
 # =============================================================================
@@ -45,7 +45,7 @@ all:
 	@echo
 	@echo '  +++ Building $(BINNAME)...'
 	@echo	
-	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME)
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQG"
 	@if test $?; then \
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
@@ -66,6 +66,30 @@ PQ:
 	   echo; echo '*************** FAILED! ***************' ; echo; \
 	 else \
 	   echo; echo '  +++ $(BINNAME) has been built with P and Q conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQG:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q and G conditions active'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQG"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q and G conditions successfully!'; \
+	   echo; \
+	 fi
+
+PQGT1:
+	@echo
+	@echo '  +++ Building $(BINNAME) with P, Q, G and T_1 conditions'
+	@echo	
+	$(MAKE) $(BRIGHT_ROOT)/$(BINNAME) DEFS="-DPQGT1"
+	@if test $?; then \
+	   echo; echo '*************** FAILED! ***************' ; echo; \
+	 else \
+	   echo; echo '  +++ $(BINNAME) has been built with P, Q, G and T_1 conditions successfully!'; \
 	   echo; \
 	 fi
 
@@ -90,7 +114,7 @@ PQ:
 # -----------------------------------------------------------------------------
 $(BRIGHT_ROOT)/$(BINNAME):	Makefile $(OBJ) 
 	@echo; echo "Linker: creating $(BRIGHT_ROOT)/$(BINNAME) ..."
-	$(CXX) $(LDFLAGS) $(SFLAGS) -o $(BRIGHT_ROOT)/$(BINNAME) $(OBJ) $(LIBS)
+	$(CXX) $(LDFLAGS) $(SFLAGS) -o $(BRIGHT_ROOT)/$(BINNAME) $(OBJ)
 
 # -----------------------------------------------------------------------------
 #   Create everything newly from scratch
@@ -108,6 +132,7 @@ clean:
 
 doc:
 	doxygen doc-config
+
 
 
 # ====================== End of file 'Makefile.in' ========================== #
